### ISSUE TITLE
Waterfall effects on the RD-180

### ISSUE THREAD

**Issue by Cheekiii** [vevladdd/ROE-Waterfall#3]
I have not tested the whole RD-170 series yet but the RD-180 does not have any sounds or visual effects after installing the newest mod version, the other engines still work.

**Comment by vevladdd** [comment]
Everything seems to work on my RD-180. 
![pic](https://user-images.githubusercontent.com/67288788/111072559-cd324b00-84e3-11eb-8e8a-d2e9ecca97f2.png)
Please, check your install, the readme was updated recently.

**Comment by Cheekiii** [comment]
got the latest version of the mod + reinstalled ROE, still no luck.
everything else seems to work though

**Comment by vevladdd** [comment]
Check your Waterfall version. Must be 0.6.1 (the latest one)

**Comment by Cheekiii** [comment]
i downloaded the version from today, yes
I will try a different version of ROE in a few minutes

**Comment by Cheekiii** [comment]
After installing different versions of mods it's finally working, not sure what i changed exactly anymore, but thanks for the help!
